### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by Kalidor64** [Aweguy/Epic-Battle-Fantasy-Ultimate-Terraria-Mod#4]
cant start a server with any version past 0.7.2 just throws this error,

Object reference not set to an instance of an object. (see server.log for full trace)
An error occurred while loading EpicBattleFantasyUltimate
The mod(s) have been automatically disabled.

System.NullReferenceException: Object reference not set to an instance of an object.
   at EpicBattleFantasyUltimate.Items.Spellbooks.SpellProtect.SetDefaults() in EpicBattleFantasyUltimate\Items\Spellbooks\SpellProtect.cs:line 17
   at Terraria.ModLoader.ItemLoader.SetDefaults(Item item, Boolean createModItem)
   at Terraria.ModLoader.Mod.SetupContent()
   at Terraria.ModLoader.ModContent.<>c.<Load>b__38_1(Mod mod)
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction)
   at Terraria.ModLoader.ModContent.Load(CancellationToken token)
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token)

and then unloads the mod

hope this can help

**Comment by Aweguy** [comment]
First of all, the mod is not made for multiplayer yet. It'll be very very wonky. I knew about the problem of not being able to start a server but didn't know what the problem was because no error came up for me, thanks for that. Also what the heck? That's just a basic function, wtf is wrong with it. I'll tamper with it. Or at worst i'll remove the item for now, was planning on reworking it anyway. Thanks for the heads up

**Comment by Aweguy** [comment]
Update: asked around and it is ALL the custom sounds and their loading in the mod. The server cannot load and play sounds so it must happen only on client side. Simple but tedious fix, adding a check in every line of code that plays a custom sound of mine. Thanks Kalidor, appreciate it :D

**Comment by Kalidor64** [comment]
Awesome hope you can fix it, love the mod keep it up.

**Comment by Aweguy** [comment]
also just to warn you, the version in tml is severely outdated. So yeah :D

**Comment by Kalidor64** [comment]
> 

Very much so.
